Checks for Wagtail 6.3 and Django 5.1
torchbox-forks/wagtail-geo-widget pull request #7
Opened 2024-11-26 12:41 UTC by nickmoreton

2024-11-27 14:34 UTC, JakubMastalerz commented
Suggestion: It's worth updating `CHANGELOG.md` even if we're not expecting the maintainer to accept this PR

2024-11-27 14:49 UTC, JakubMastalerz requested changes
Suggestion: It's worth updating CHANGELOG.md even if we're not expecting the maintainer to accept this PR

2024-11-28 09:00 UTC, nickmoreton commented
> Suggestion: It's worth updating CHANGELOG.md even if we're not expecting the maintainer to accept this PR

Thanks @JakubMastalerz Good call. I have updated that here: https://github.com/torchbox-forks/wagtail-geo-widget/pull/7/commits/b448b5c1a01fe6aba8e49269791c61ec325ff355

2024-11-28 10:16 UTC, JakubMastalerz approved these changes

2024-11-29 14:07 UTC, merged